{% for ruamel_version in ruamel_versions %}
{% for python_version in python_versions %}
- name: Mapping validation
  preconditions:
    python_version: {{ python_version }}
    ruamel version: {{ ruamel_version }}
    files:
      valid_sequence.yaml: |
        a: 1
        b: 2
        c: 3
      invalid_sequence_1.yaml: |
        a: 1
        b: 2
        d: 3
      invalid_sequence_2.yaml: |
        - 1
        - 2
        - 3
      invalid_sequence_3.yaml: |
        a: 1
        b: 2
        c: 3
        d: 4
  tags:
    - map
    - py{{ python_version }}
  scenario:
    - Run command: |
        from strictyaml import Map, Int, YAMLValidationError, load

        schema = Map({"a": Int(), "b": Int(), "c": Int()})

    - Assert True: 'load(valid_sequence, schema) == {"a": 1, "b": 2, "c": 3}'

    - Assert Exception:
        command: load(invalid_sequence_1, schema)
        exception: |
          while parsing a mapping
          unexpected key not in schema 'd'
            in "<unicode string>", line 3, column 1:
              d: '3'
              ^

    - Assert Exception:
        command: load(invalid_sequence_2, schema)
        exception: |
          when expecting a mapping
            in "<unicode string>", line 1, column 1:
              - '1'
               ^
          found non-mapping
            in "<unicode string>", line 3, column 1:
              - '3'
              ^



    - Assert Exception:
        command: load(invalid_sequence_3, schema)
        exception: |
          while parsing a mapping
          unexpected key not in schema 'd'
            in "<unicode string>", line 4, column 1:
              d: '4'
              ^
    
{% endfor %}
{% endfor %}
